/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productos.presentation;

import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import productos.Productos;
import productos.logic.Producto;
import productos.logic.Tipo;

/**
 *
 * @author ExtremeTech
 */
public class ProductosView extends javax.swing.JFrame implements java.util.Observer {

    ControllerProductos controller;
    ModelProductos model;

    /**
     * Creates new form ProductosView
     */
    public ProductosView() {
        initComponents();
    }

    public ControllerProductos getController() {
        return controller;
    }

    public void setController(ControllerProductos controller) {
        this.controller = controller;
    }

    public ModelProductos getModel() {
        return model;

    }

    public void setModel(ModelProductos model) {
        this.model = model;
        model.addObserver(this);
    }

    Producto toProducto() {
        Producto result = new Producto();
        result.setCodigo(this.codigotxt.getText());
        result.setNombre(this.nombretxt.getText());
        result.setImportado(this.cbimportado.isSelected());
        result.setPrecio(Integer.parseInt(this.preciotxt.getText()));
        result.setTipo((Tipo) this.CBagregar.getSelectedItem());
        return result;
    }

    Producto toProductosearch() {
        Producto result = new Producto();
        result.setNombre(this.nombrebuscar.getText());
        result.setTipo((Tipo) this.CBtiposbuscar.getSelectedItem());
        return result;
    }

    public void limpiarErrores() {
        this.lcodigo.setForeground(Productos.COLOR_OK);
        this.lnombre.setForeground(Productos.COLOR_OK);
        this.lprecio.setForeground(Productos.COLOR_OK);
        this.ltipo.setForeground(Productos.COLOR_OK);
        this.lnombreB.setForeground(Productos.COLOR_OK);
        this.ltipobuscar.setForeground(Productos.COLOR_OK);
    }

    boolean validar() {
        boolean error = false;
        this.lcodigo.setForeground(Productos.COLOR_OK);
        if (this.codigotxt.getText().isEmpty()) {
            this.lcodigo.setForeground(Productos.COLOR_ERROR);
            error = true;
        }
        this.lnombre.setForeground(Productos.COLOR_OK);
        if (this.nombretxt.getText().isEmpty()) {
            this.lnombre.setForeground(Productos.COLOR_ERROR);
            error = true;
        }
        this.lprecio.setForeground(Productos.COLOR_OK);
        if (this.preciotxt.getText().isEmpty()) {
            this.lprecio.setForeground(Productos.COLOR_ERROR);
            error = true;
        }
        this.ltipo.setForeground(Productos.COLOR_OK);
        if (this.CBagregar.getSelectedIndex() == 0) {
            this.ltipo.setForeground(Productos.COLOR_ERROR);
            error = true;
        }
        return error;
    }

    boolean validar_nombre() {
        boolean error = false;
        this.lnombreB.setForeground(Productos.COLOR_OK);
        if (this.nombrebuscar.getText().isEmpty()) {
            this.lnombreB.setForeground(Productos.COLOR_ERROR);
            error = true;
        }
        return error;
    }

    boolean validar_tipo() {
        boolean error = false;
        this.ltipobuscar.setForeground(Productos.COLOR_OK);
        if (this.CBtiposbuscar.getSelectedIndex() == 0) {
            this.ltipobuscar.setForeground(Productos.COLOR_ERROR);
            error = true;
        }
        return error;
    }

    public void limpiar_agregar() {
        this.codigotxt.setText("");
        this.nombretxt.setText("");
        this.preciotxt.setText("");
        this.CBagregar.setSelectedIndex(0);
        this.cbimportado.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        lnombreB = new javax.swing.JLabel();
        buscarnombre = new javax.swing.JButton();
        ltipobuscar = new javax.swing.JLabel();
        nombrebuscar = new javax.swing.JTextField();
        buscartipo = new javax.swing.JButton();
        CBtiposbuscar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        productostable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lcodigo = new javax.swing.JLabel();
        codigotxt = new javax.swing.JTextField();
        lnombre = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        lprecio = new javax.swing.JLabel();
        preciotxt = new javax.swing.JTextField();
        limportado = new javax.swing.JLabel();
        cbimportado = new javax.swing.JCheckBox();
        ltipo = new javax.swing.JLabel();
        CBagregar = new javax.swing.JComboBox<>();
        btnAgegar = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lnombreB.setText("Nombre");

        buscarnombre.setText("Buscar");
        buscarnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarnombreActionPerformed(evt);
            }
        });

        ltipobuscar.setText("Tipo");

        buscartipo.setText("Buscar");
        buscartipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscartipoActionPerformed(evt);
            }
        });

        productostable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(productostable);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lcodigo.setText("Codigo");

        lnombre.setText("Nombre");

        lprecio.setText("Precio");

        limportado.setText("Importado");

        ltipo.setText("Tipo");

        btnAgegar.setText("Agregar");
        btnAgegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgegarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(limportado)
                            .addComponent(ltipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbimportado)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CBagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgegar))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lprecio)
                            .addGap(29, 29, 29)
                            .addComponent(preciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lnombre)
                                .addComponent(lcodigo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(codigotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(nombretxt)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcodigo)
                    .addComponent(codigotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnombre)
                    .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lprecio)
                    .addComponent(preciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limportado)
                    .addComponent(cbimportado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ltipo)
                    .addComponent(CBagregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgegar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lnombreB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombrebuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarnombre)
                        .addGap(38, 38, 38)
                        .addComponent(ltipobuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBtiposbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscartipo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnombreB)
                    .addComponent(buscarnombre)
                    .addComponent(ltipobuscar)
                    .addComponent(nombrebuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscartipo)
                    .addComponent(CBtiposbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarnombreActionPerformed
        if (!validar_nombre()) {
            try {
                controller.buscar(this.toProductosearch());
            } catch (Exception ex) {

            }
        }
    }//GEN-LAST:event_buscarnombreActionPerformed

    private void buscartipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscartipoActionPerformed
        if (!validar_tipo()) {
            try {
                controller.buscar(this.toProductosearch());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se encontro ninguna coincidencia", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buscartipoActionPerformed

    private void btnAgegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgegarActionPerformed
        if (!validar()) {
            try {
                controller.agregar(this.toProducto());
                limpiar_agregar();
                JOptionPane.showMessageDialog(this, "Datos registrados", "OK", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "error al ingresar", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAgegarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Tipo> CBagregar;
    private javax.swing.JComboBox<Tipo> CBtiposbuscar;
    private javax.swing.JButton btnAgegar;
    private javax.swing.JButton buscarnombre;
    private javax.swing.JButton buscartipo;
    private javax.swing.JCheckBox cbimportado;
    private javax.swing.JTextField codigotxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lcodigo;
    private javax.swing.JLabel limportado;
    private javax.swing.JLabel lnombre;
    private javax.swing.JLabel lnombreB;
    private javax.swing.JLabel lprecio;
    private javax.swing.JLabel ltipo;
    private javax.swing.JLabel ltipobuscar;
    private javax.swing.JTextField nombrebuscar;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JTextField preciotxt;
    private javax.swing.JTable productostable;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        this.limpiarErrores();
        Producto filtro = model.getFilter();
        this.productostable.setModel(model.getProductos());
        this.CBagregar.setModel(model.getCombotiposask());
        this.CBtiposbuscar.setModel(model.getCombotiposadd());
        this.fromProducto(filtro);
        this.CBagregar.setSelectedItem(0);
        this.CBtiposbuscar.setSelectedItem(0);
    }

    public void fromProducto(Producto actual) {
        if (!actual.getTipo().getIdTipo().equals("")) {
            this.CBtiposbuscar.setSelectedItem(actual.getTipo());
        } else {
            this.CBtiposbuscar.setSelectedIndex(0);
        }

        this.nombrebuscar.setText(actual.getNombre());
    }
}
